### ISSUE TITLE
[Bug]: Push to repo after update von README.md fails (remote updates, pull first)

### ISSUE THREAD

**Issue by davidsneighbour** [gautamkrishnar/blog-post-workflow#36]
1. Creating the action workflow
2. Run the action
3. pull and load the changes locally
4. change the README.md locally
5. commit and push to repo on Github
6. Run the action

Result: 

```
Run gautamkrishnar/blog-post-workflow@master
  with:
    max_post_count: 4
    feed_list: https://***.rss
    comment_tag_name: DISCOURSE
    template: - ($date) [$title]($url)$newline
    date_format: mmmm d, yyyy at h:MM TT
    commit_message: chore: update README.md with latest gohugo.io posts
    gh_token: ***
    readme_path: ./README.md
    disable_sort: false
    filter_comments: medium,stackoverflow/Comment by $author/,stackexchange/Comment by $author/
    user_agent: rss-parser
    accept_header: application/rss+xml
    committer_username: blog-post-bot
    committer_email: blog-post-bot@example.com
https://***.rss runner succeeded. Post count: 50
Writing to ./README.md
Started: git config --global user.email blog-post-bot@example.com
Started: git remote set-url origin https://***@***.git
Started: git config --global user.name blog-post-bot
Started: git add ./README.md
Started: git commit -m chore: update README.md with latest gohugo.io posts
[master bf1025a] chore: update README.md with latest gohugo.io posts
 1 file changed, 2 insertions(+), 2 deletions(-)
Started: git push
To https://***.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://***.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
(node:2466) UnhandledPromiseRejectionWarning: Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/gautamkrishnar/blog-post-workflow/master/dist/blog-post-workflow.js:116:945)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:2466) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2466) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The action should pull first from the repo before it updates the README.md.

**Comment by davidsneighbour** [comment]
It appears this happens only if the Action is manually re-run. The next automatic scheduled action did work (this time).

**Comment by gautamkrishnar** [comment]
@davidsneighbour thanks a lot for reporting. This has been fixed on https://github.com/gautamkrishnar/blog-post-workflow/releases/tag/1.3.6
